url: https://attajak.github.io
baseurl: /hello-world

title: Hello World!
description: สวัสดีชาวโลก

github_username: attajak
twitter_username: attajak
facebook_username: attajak

theme: jekyll-theme-slate

plugins:
  - jekyll-readme-index
