# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

# gem "jekyll"

gem "github-pages", group: :jekyll_plugins

# gem "minimal-mistakes-jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-include-cache"
  gem "jekyll-gist"
end

gem "webrick"

gem "faraday-retry"
