# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.3.3"

gem "minimal-mistakes-jekyll", "~> 4.24"

gem "jekyll-compose", "~> 0.12.0", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-include-cache"
end

gem "webrick"

gem "faraday-retry", "~> 2.2"
